# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZv2SLDxOwYPcI04nqido0EnGzdK74dE
"""

student1 = (101, "Shreya", "CSE", 85)


student_list = [
    student1,
    (102, "Rahul", "ENTC", 78),
    (103, "Priya", "IT", 92)
]


students = {
    101: {"Name": "Shreya", "Branch": "CSE", "Marks": 85},
    102: {"Name": "Rahul", "Branch": "ENTC", "Marks": 78},
    103: {"Name": "Priya", "Branch": "IT", "Marks": 92}
}


students[104] = {
    "Name": "Amit",
    "Branch": "Mechanical",
    "Marks": 81
}

del students[102]


students[103]["Branch"] = "CSE"
students[103]["Marks"] = 95


print("Final Student Records:")

for roll_no, details in students.items():
    print("Roll Number:", roll_no)
    print("Name:", details["Name"])
    print("Branch:", details["Branch"])
    print("Marks:", details["Marks"])
    print("----------------------")