# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZv2SLDxOwYPcI04nqido0EnGzdK74dE
"""

def is_right_angled(a, b, c):
    # Find the largest side
    sides = [a, b, c]
    sides.sort()

    # Apply Pythagoras theorem
    if sides[0]**2 + sides[1]**2 == sides[2]**2:
        return True
    else:
        return False


# Accept three sides from the user
a = float(input("Enter first side: "))
b = float(input("Enter second side: "))
c = float(input("Enter third side: "))

# Check the triangle
if is_right_angled(a, b, c):
    print("The triangle is a right-angled triangle.")
else:
    print("The triangle is not a right-angled triangle.")